vim.g['airline_powerline_fonts'] = 1
vim.g['airline_left_sep'] = ''
vim.g['airline_right_sep'] = ''
vim.g['airline_theme'] = 'kolor'
--vim.g['airline#extensions#tabline#enabled'] = 1
vim.g['airline#extensions#tabline#buffer_nr_show'] = 1
vim.g['airline#extensions#tabline#fnamemod'] = ':t'
vim.g['airline#extensions#branch#enabled'] = 1
vim.g['airline#extensions#whitespace#enabled'] = 1
vim.g['airline#extensions#ale#enabled'] = 1
vim.g['airline#extensions#syntastic#enabled'] = 1 -- Enables syntastic extension
vim.g['airline#extensions#undotree#enabled'] = 1 -- Enables undotree extension
vim.g['airline#extensions#tagbar#enabled'] = 1 -- Enables tagbar extension
vim.g['airline#extensions#quickfix#enabled'] = 1 -- Enables quickfix extension
vim.g['airline#extensions#keymap#enabled'] = 1 -- Enables keymap extension
vim.g['airline#extensions#hunks#enabled'] = 1 -- Enables hunks extension
vim.g['airline_skip_empty_sections'] = 1 -- Skips empty sections
vim.g['airline#extensions#wordcount#enabled'] = 1 -- Enables wordcount extension
vim.g['airline#extensions#tmuxline#enabled'] = 1 -- Enables tmuxline extension
vim.g['airline#extensions#tagbar#flags'] = 's' -- Shows scope flags in tagbar
vim.g['airline#extensions#ale#open_errors'] = 1 -- Opens ALE on errors
